# Generated by Django 3.0.5 on 2021-11-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('year', models.CharField(max_length=4, verbose_name='Año')),
                ('front', models.ImageField(default='null', upload_to='', verbose_name='Portada')),
                ('categories', models.ManyToManyField(to='libros.Category', verbose_name='Categorías')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
            },
        ),
    ]
